# Generated by Django 4.0.6 on 2022-08-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(default='Nom', max_length=30, verbose_name="Nom de l'employé")),
                ('e_fname', models.CharField(default='Prénom', max_length=30, verbose_name="Prénom de l'employé")),
                ('y_worked', models.IntegerField(verbose_name="Années d'ancienneté")),
                ('job', models.CharField(choices=[('salle', 'Salle'), ('cuisine', 'Cuisine'), ('gestion', 'Gestion')], default='Salle, Cuisine ou Gestion', max_length=30, verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=30, verbose_name='Nom du restaurant')),
                ('tva_nr', models.CharField(max_length=15, verbose_name='Numéro de TVA')),
                ('y_launch', models.IntegerField(default='1998', verbose_name='Année de lancement')),
                ('email_address', models.CharField(default='monadresse@mail.com', max_length=30, verbose_name='Adresse mail')),
                ('city', models.CharField(default='Ville', max_length=30, verbose_name='Ville')),
                ('has_employee', models.ManyToManyField(to='R_Restaurant_App.employee')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='0', max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='date et heure')),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('r_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_Restaurant_App.restaurant')),
                ('user', models.ManyToManyField(related_name='Utilisateur', to='R_Restaurant_App.users')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_r',
            field=models.ManyToManyField(related_name='Travaille', to='R_Restaurant_App.restaurant'),
        ),
    ]
