# Generated by Django 4.0.6 on 2022-08-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_Restaurant_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_r',
            field=models.ManyToManyField(blank=True, related_name='Travaille', to='R_Restaurant_App.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='has_employee',
            field=models.ManyToManyField(blank=True, to='R_Restaurant_App.employee'),
        ),
    ]
