# Generated by Django 4.0.6 on 2022-08-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_Restaurant_App', '0002_alter_employee_work_r_alter_restaurant_has_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_r',
            field=models.ManyToManyField(blank=True, to='R_Restaurant_App.restaurant'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='Utilisateur', to='R_Restaurant_App.users'),
        ),
    ]
