# Generated by Django 4.0.6 on 2022-08-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_Restaurant_App', '0003_alter_employee_work_r_alter_ratings_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='e_fname',
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_name',
            field=models.CharField(default='Nom', max_length=30, verbose_name="Nom et prénom de l'employé"),
        ),
    ]
