# Generated by Django 4.0.6 on 2022-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_Restaurant_App', '0004_remove_employee_e_fname_alter_employee_e_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='has_employee',
            field=models.ManyToManyField(to='R_Restaurant_App.employee'),
        ),
    ]
